"""Canonical-snapshot reconciliation script (B-16).

Runs every Cypher query the evaluation report needs in a single
read-transaction against the live Neo4j instance, captures one wall-clock
timestamp, and writes a single
``outputs/metrics/canonical_snapshot.json`` that all report sections cite
as the source of truth for numerical values.

Motivation: the evaluation report is composed from three independently
produced JSON files (``eda_statistics.json``, ``semantic_density.json``,
the FAIR / alignment / validity JSONs), each generated by a different
command at different times. The report has been observed to render
mutually inconsistent numbers when those files drift out of temporal
alignment. This script forces every figure / table to read from one
snapshot, captured atomically, with the snapshot timestamp displayed
prominently in the report header.

CLI::

    python -m metrics.reconcile
    python -m metrics.reconcile --output outputs/metrics/canonical_snapshot.json

The script never writes to the graph. It is safe to run against a
production database. It does not stop or restart the database.
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


PROJECT_ROOT = Path(__file__).resolve().parents[1]


# ---------------------------------------------------------------------------
# Connector protocol
# ---------------------------------------------------------------------------


class Connector:
    def run_query(self, query: str, parameters: dict[str, Any] | None = None) -> list[dict[str, Any]]:
        raise NotImplementedError


def _scalar(rows: list[dict[str, Any]], key: str, default: int = 0) -> int:
    if not rows:
        return default
    val = rows[0].get(key, default)
    try:
        return int(val) if val is not None else default
    except (TypeError, ValueError):
        return default


# ---------------------------------------------------------------------------
# Snapshot dataclass
# ---------------------------------------------------------------------------


@dataclass
class CanonicalSnapshot:
    schema_version: int
    timestamp: str
    graph_uri: str
    run_id: str

    # Aggregate
    node_total: int = 0
    edge_total: int = 0
    distinct_node_labels: int = 0
    distinct_relationship_types: int = 0

    # Clinical entity layer
    patients: int = 0
    visits: int = 0
    diagnoses: int = 0
    cognitive_assessments: int = 0
    biomarkers_total: int = 0
    biomarkers_csf: int = 0
    biomarkers_with_loinc: int = 0
    biomarkers_csf_with_loinc: int = 0
    brain_regions: int = 0
    family_members: int = 0
    image_nodes: int = 0

    # Ontology layer (per-source counts)
    ontology_concepts_by_source: dict[str, int] = field(default_factory=dict)
    ontology_concepts_total: int = 0

    # AlzKB layer
    alzkb_concepts: int = 0
    same_as_edges: int = 0
    alzkb_relates_to_edges: int = 0

    # Qualified-reference edges
    maps_to_edges: int = 0
    is_a_edges: int = 0
    classified_as_edges: int = 0

    # URI coverage (canonical denominator)
    edges_with_uri: int = 0
    nodes_with_ontology_code: int = 0

    # Per-relationship-type cardinalities (subset relevant for the report)
    relationship_cardinalities: dict[str, int] = field(default_factory=dict)
    node_label_cardinalities: dict[str, int] = field(default_factory=dict)

    # Derived rates (computed from the above; convenience for the report)
    edge_uri_coverage: float = 0.0
    node_ontology_coverage: float = 0.0
    biomarkers_csf_loinc_rate: float = 0.0
    biomarkers_overall_loinc_rate: float = 0.0

    duration_seconds: float = 0.0
    notes: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


# ---------------------------------------------------------------------------
# Canonical query battery
# ---------------------------------------------------------------------------


_AGG_NODE_TOTAL = "MATCH (n) RETURN count(n) AS n"
_AGG_EDGE_TOTAL = "MATCH ()-[r]->() RETURN count(r) AS n"
_DISTINCT_LABELS = "MATCH (n) UNWIND labels(n) AS lbl WITH DISTINCT lbl RETURN count(lbl) AS n"
_DISTINCT_REL_TYPES = "MATCH ()-[r]->() WITH DISTINCT type(r) AS t RETURN count(t) AS n"

_PATIENTS = "MATCH (p:Patient) RETURN count(p) AS n"
_VISITS = "MATCH (v:Visit) RETURN count(v) AS n"
_DIAGNOSES = "MATCH (d:Diagnosis) RETURN count(d) AS n"
_COG_ASSESSMENTS = "MATCH (c:CognitiveAssessment) RETURN count(c) AS n"
_BIOMARKERS_TOTAL = "MATCH (b:Biomarker) RETURN count(b) AS n"
_BIOMARKERS_CSF = (
    "MATCH (b:Biomarker) "
    "WHERE b.biomarker_type IS NOT NULL "
    "  AND toUpper(coalesce(b.biomarker_type,'')) CONTAINS 'CSF' "
    "RETURN count(b) AS n"
)
_BIOMARKERS_WITH_LOINC = (
    "MATCH (b:Biomarker) WHERE b.loinc_code IS NOT NULL RETURN count(b) AS n"
)
_BIOMARKERS_CSF_WITH_LOINC = (
    "MATCH (b:Biomarker) "
    "WHERE b.biomarker_type IS NOT NULL "
    "  AND toUpper(coalesce(b.biomarker_type,'')) CONTAINS 'CSF' "
    "  AND b.loinc_code IS NOT NULL "
    "RETURN count(b) AS n"
)
_BRAIN_REGIONS = "MATCH (br:BrainRegion) RETURN count(br) AS n"
_FAMILY_MEMBERS = "MATCH (f:FamilyMember) RETURN count(f) AS n"
_IMAGE_NODES = "MATCH (i:ImageNode) RETURN count(i) AS n"

_ONTOLOGY_CONCEPTS_BY_SOURCE = (
    "MATCH (o:OntologyConcept) "
    "RETURN coalesce(o.source_ontology,'UNKNOWN') AS source, count(o) AS n "
    "ORDER BY source"
)

_ALZKB_CONCEPTS = "MATCH (a:AlzKBConcept) RETURN count(a) AS n"
_SAME_AS = "MATCH ()-[r:SAME_AS]->() RETURN count(r) AS n"
_ALZKB_RELATES_TO = "MATCH ()-[r:ALZKB_RELATES_TO]->() RETURN count(r) AS n"

_MAPS_TO = "MATCH ()-[r:MAPS_TO]->() RETURN count(r) AS n"
_IS_A = "MATCH ()-[r:IS_A]->() RETURN count(r) AS n"
_CLASSIFIED_AS = "MATCH ()-[r:CLASSIFIED_AS]->() RETURN count(r) AS n"

_EDGES_WITH_URI = (
    "MATCH ()-[r]->() "
    "RETURN count(r) AS total, "
    "       count(CASE WHEN r.uri IS NOT NULL THEN 1 END) AS with_uri"
)

_NODES_WITH_ONTOLOGY = (
    "MATCH (n) "
    "WITH n, ((n.snomed_code IS NOT NULL OR n.loinc_code IS NOT NULL "
    "          OR n.uberon_code IS NOT NULL OR n.icd10_code IS NOT NULL "
    "          OR n.mondo_code IS NOT NULL OR n.hpo_code IS NOT NULL "
    "          OR n.ontology_uri IS NOT NULL OR n.uri IS NOT NULL "
    "          OR n.rdf_type IS NOT NULL) "
    "         OR 'OntologyConcept' IN labels(n)) AS ok "
    "RETURN count(n) AS total, count(CASE WHEN ok THEN 1 END) AS with_ontology"
)

_REL_TYPE_BREAKDOWN = (
    "MATCH ()-[r]->() "
    "WITH type(r) AS rel_type, count(r) AS n "
    "RETURN rel_type, n ORDER BY n DESC"
)

_NODE_LABEL_BREAKDOWN = (
    "MATCH (n) UNWIND labels(n) AS lbl "
    "WITH lbl, count(n) AS n "
    "RETURN lbl, n ORDER BY n DESC"
)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def reconcile(connector: Connector, *, graph_uri: str = "(unknown)") -> CanonicalSnapshot:
    """Run the canonical query battery and return a single snapshot."""

    import time

    started = time.time()
    ts = datetime.now(timezone.utc).isoformat(timespec="seconds")
    run_id = ts.replace(":", "").replace("-", "").replace("+0000", "Z").replace("+00:00", "Z")

    snap = CanonicalSnapshot(
        schema_version=1,
        timestamp=ts,
        graph_uri=graph_uri,
        run_id=run_id,
    )

    # Aggregate
    snap.node_total = _scalar(connector.run_query(_AGG_NODE_TOTAL), "n")
    snap.edge_total = _scalar(connector.run_query(_AGG_EDGE_TOTAL), "n")
    snap.distinct_node_labels = _scalar(connector.run_query(_DISTINCT_LABELS), "n")
    snap.distinct_relationship_types = _scalar(connector.run_query(_DISTINCT_REL_TYPES), "n")

    # Clinical entities
    snap.patients = _scalar(connector.run_query(_PATIENTS), "n")
    snap.visits = _scalar(connector.run_query(_VISITS), "n")
    snap.diagnoses = _scalar(connector.run_query(_DIAGNOSES), "n")
    snap.cognitive_assessments = _scalar(connector.run_query(_COG_ASSESSMENTS), "n")
    snap.biomarkers_total = _scalar(connector.run_query(_BIOMARKERS_TOTAL), "n")
    snap.biomarkers_csf = _scalar(connector.run_query(_BIOMARKERS_CSF), "n")
    snap.biomarkers_with_loinc = _scalar(connector.run_query(_BIOMARKERS_WITH_LOINC), "n")
    snap.biomarkers_csf_with_loinc = _scalar(connector.run_query(_BIOMARKERS_CSF_WITH_LOINC), "n")
    snap.brain_regions = _scalar(connector.run_query(_BRAIN_REGIONS), "n")
    snap.family_members = _scalar(connector.run_query(_FAMILY_MEMBERS), "n")
    snap.image_nodes = _scalar(connector.run_query(_IMAGE_NODES), "n")

    # Ontology layer
    rows = connector.run_query(_ONTOLOGY_CONCEPTS_BY_SOURCE)
    by_source = {str(r.get("source") or "UNKNOWN"): int(r.get("n") or 0) for r in rows}
    snap.ontology_concepts_by_source = by_source
    snap.ontology_concepts_total = sum(by_source.values())

    # AlzKB
    snap.alzkb_concepts = _scalar(connector.run_query(_ALZKB_CONCEPTS), "n")
    snap.same_as_edges = _scalar(connector.run_query(_SAME_AS), "n")
    snap.alzkb_relates_to_edges = _scalar(connector.run_query(_ALZKB_RELATES_TO), "n")

    # Qualified-reference edges
    snap.maps_to_edges = _scalar(connector.run_query(_MAPS_TO), "n")
    snap.is_a_edges = _scalar(connector.run_query(_IS_A), "n")
    snap.classified_as_edges = _scalar(connector.run_query(_CLASSIFIED_AS), "n")

    # URI coverage (canonical denominator)
    rows = connector.run_query(_EDGES_WITH_URI)
    if rows:
        snap.edge_total = int(rows[0].get("total") or snap.edge_total)
        snap.edges_with_uri = int(rows[0].get("with_uri") or 0)
    rows = connector.run_query(_NODES_WITH_ONTOLOGY)
    if rows:
        snap.nodes_with_ontology_code = int(rows[0].get("with_ontology") or 0)

    # Per-rel-type and per-label breakdowns
    snap.relationship_cardinalities = {
        str(r.get("rel_type")): int(r.get("n") or 0)
        for r in connector.run_query(_REL_TYPE_BREAKDOWN)
    }
    snap.node_label_cardinalities = {
        str(r.get("lbl")): int(r.get("n") or 0)
        for r in connector.run_query(_NODE_LABEL_BREAKDOWN)
    }

    # Derived rates
    if snap.edge_total > 0:
        snap.edge_uri_coverage = round(snap.edges_with_uri / snap.edge_total, 4)
    if snap.node_total > 0:
        snap.node_ontology_coverage = round(snap.nodes_with_ontology_code / snap.node_total, 4)
    if snap.biomarkers_csf > 0:
        snap.biomarkers_csf_loinc_rate = round(
            snap.biomarkers_csf_with_loinc / snap.biomarkers_csf, 4)
    if snap.biomarkers_total > 0:
        snap.biomarkers_overall_loinc_rate = round(
            snap.biomarkers_with_loinc / snap.biomarkers_total, 4)

    snap.duration_seconds = round(time.time() - started, 2)

    # Sanity-check notes — surface internal inconsistencies the user can act on
    notes: list[str] = []
    # Cross-check biomarker LOINC story
    if snap.biomarkers_csf > 0 and snap.biomarkers_total > snap.biomarkers_csf:
        notes.append(
            f"Biomarker LOINC coverage breaks down as CSF "
            f"({snap.biomarkers_csf_with_loinc}/{snap.biomarkers_csf}, "
            f"{snap.biomarkers_csf_loinc_rate:.1%}) vs overall "
            f"({snap.biomarkers_with_loinc}/{snap.biomarkers_total}, "
            f"{snap.biomarkers_overall_loinc_rate:.1%}). The PHASE1 '100%' "
            f"claim refers to the CSF subset only; the report should "
            f"distinguish the two."
        )
    snap.notes = notes
    return snap


def write_json(snapshot: CanonicalSnapshot, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(snapshot.to_dict(), f, indent=2, ensure_ascii=False)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="python -m metrics.reconcile",
        description="Capture a canonical graph-state snapshot for the evaluation report (B-16).",
    )
    p.add_argument("--output", type=Path,
                   default=PROJECT_ROOT / "outputs" / "metrics" / "canonical_snapshot.json",
                   help="Path for the canonical-snapshot JSON.")
    p.add_argument("--neo4j-uri", default=None)
    p.add_argument("--user", default=None)
    p.add_argument("--password", default=None)
    p.add_argument("--quiet", action="store_true")
    return p


def _resolve_credentials(args: argparse.Namespace) -> tuple[str, str, str]:
    uri, user, pw = args.neo4j_uri, args.user, args.password
    if not (uri and user and pw):
        from utils.env_loader import load_config

        cfg = load_config()
        uri = uri or cfg.get("neo4j_uri")
        user = user or cfg.get("neo4j_user", "neo4j")
        pw = pw or cfg.get("neo4j_password")
    if not (uri and user and pw):
        raise RuntimeError("Neo4j credentials missing")
    return uri, user, pw


def main(argv: list[str] | None = None) -> int:
    args = _build_arg_parser().parse_args(argv)
    logging.basicConfig(
        level=logging.WARNING if args.quiet else logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )

    try:
        uri, user, pw = _resolve_credentials(args)
    except Exception as exc:
        logger.error("%s", exc)
        return 2

    from utils.neo4j_connector import Neo4jConnector

    connector = Neo4jConnector(uri=uri, user=user, password=pw)
    try:
        snap = reconcile(connector, graph_uri=uri)
    finally:
        connector.close()

    out_path = args.output
    if not out_path.is_absolute():
        out_path = PROJECT_ROOT / out_path
    write_json(snap, out_path)

    logger.info("Wrote canonical snapshot to %s", out_path)
    print(json.dumps(
        {
            "timestamp": snap.timestamp,
            "run_id": snap.run_id,
            "node_total": snap.node_total,
            "edge_total": snap.edge_total,
            "edge_uri_coverage": snap.edge_uri_coverage,
            "ontology_concepts_total": snap.ontology_concepts_total,
            "ontology_concepts_by_source": snap.ontology_concepts_by_source,
            "biomarkers_total": snap.biomarkers_total,
            "biomarkers_csf": snap.biomarkers_csf,
            "biomarkers_csf_loinc_rate": snap.biomarkers_csf_loinc_rate,
            "biomarkers_overall_loinc_rate": snap.biomarkers_overall_loinc_rate,
            "alzkb_concepts": snap.alzkb_concepts,
            "same_as_edges": snap.same_as_edges,
            "notes": snap.notes,
        },
        indent=2,
    ))
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
